version: "3"

services:

  app:
    container_name: flask_app
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
    - database:/app/database

  db:
    container_name: sqlite
    image: nouchka/sqlite3
    stdin_open: true
    tty: true
    volumes:
      - database:/database
    ports:
      - '9000:9000'

volumes:
  database:
