version: "3"

services:

  proxy:
    container_name: nginx_server
    image: nginx:alpine
    ports:
      - '8080:8080'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  app:
    container_name: flask_app
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
    - database:/app/database

  db:
    container_name: sqlite
    image: nouchka/sqlite3
    stdin_open: true
    tty: true
    volumes:
      - database:/database
    ports:
      - '9000:9000'

volumes:
  database:
